// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgtuvatpnjnynxpzcnrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBndHV2YXRwbmpueW54cHpjbnJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTU3NTAsImV4cCI6MjA3NDUzMTc1MH0.T1neNMOpnCU_U5VqRo2WVrtuwgzHQSZ6nKmgowDJfxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});