name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # updated to v4
        with:
          node-version: '20'        # use latest LTS (20)

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Setup Java
        uses: actions/setup-java@v4 # updated to v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Add Android platform (Capacitor/React)
        run: npx cap add android || true

      - name: Sync Capacitor
        run: npx cap sync || true

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4   # updated to v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
